name: stats
dependencies:
  - numpy
  - pandas
  - streamlit
  - nltk
  - wordcloud
  - plotly.express
  - chart_studio
  - bs4
  - urllib
  - request
  - requests
  - string
  - heapq
  - time
  - re
